# Translations template for manila.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the manila project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: manila 2015.1.dev129\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-12 06:12+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: manila/context.py:96
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: manila/exception.py:69
msgid "An unknown exception occurred."
msgstr ""

#: manila/exception.py:111
msgid "Exception due to network failure."
msgstr ""

#: manila/exception.py:115
#, python-format
msgid "Bad network configuration: %(reason)s."
msgstr ""

#: manila/exception.py:119
msgid "Not authorized."
msgstr ""

#: manila/exception.py:124
msgid "User does not have admin privileges."
msgstr ""

#: manila/exception.py:128
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: manila/exception.py:132
msgid "Unacceptable parameters."
msgstr ""

#: manila/exception.py:137
msgid "The request is invalid."
msgstr ""

#: manila/exception.py:141
msgid "The results are invalid."
msgstr ""

#: manila/exception.py:145
#, python-format
msgid "Invalid input received: %(reason)s."
msgstr ""

#: manila/exception.py:149
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: manila/exception.py:153
#, python-format
msgid "Invalid host: %(reason)s"
msgstr ""

#: manila/exception.py:159 manila/exception.py:469 manila/exception.py:473
#: manila/exception.py:477 manila/exception.py:481 manila/exception.py:510
#, python-format
msgid "%(err)s"
msgstr ""

#: manila/exception.py:163
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: manila/exception.py:167
msgid "Resource could not be found."
msgstr ""

#: manila/exception.py:173
msgid "Resource is in use."
msgstr ""

#: manila/exception.py:177
#, python-format
msgid "Share network %(share_network_id)s could not be found."
msgstr ""

#: manila/exception.py:181
#, python-format
msgid "Share server %(share_server_id)s could not be found."
msgstr ""

#: manila/exception.py:185
#, python-format
msgid "Share server could not be found by filters: %(filters_description)s."
msgstr ""

#: manila/exception.py:190
#, python-format
msgid "Share server %(share_server_id)s is in use."
msgstr ""

#: manila/exception.py:194
#, python-format
msgid "Share server %(share_server_id)s failed on creation."
msgstr ""

#: manila/exception.py:198
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: manila/exception.py:202
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: manila/exception.py:206
#, python-format
msgid "Scheduler host filter %(filter_name)s could not be found."
msgstr ""

#: manila/exception.py:210
#, python-format
msgid "Scheduler host weigher %(weigher_name)s could not be found."
msgstr ""

#: manila/exception.py:214
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: manila/exception.py:218
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: manila/exception.py:222
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s."
msgstr ""

#: manila/exception.py:227
msgid "Quota could not be found."
msgstr ""

#: manila/exception.py:231
#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s."
msgstr ""

#: manila/exception.py:236
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: manila/exception.py:240
#, python-format
msgid "Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:245
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:249
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: manila/exception.py:253
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: manila/exception.py:257
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: manila/exception.py:261
#, python-format
msgid "Quota exceeded for resources: %(overs)s."
msgstr ""

#: manila/exception.py:265
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: manila/exception.py:269
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: manila/exception.py:274
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: manila/exception.py:278
#, python-format
msgid "Migration error: %(reason)s."
msgstr ""

#: manila/exception.py:282
#, python-format
msgid "Malformed message body: %(reason)s."
msgstr ""

#: manila/exception.py:286
#, python-format
msgid "Could not find config at %(path)s."
msgstr ""

#: manila/exception.py:290
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s."
msgstr ""

#: manila/exception.py:294
#, python-format
msgid "No valid host was found. %(reason)s."
msgstr ""

#: manila/exception.py:298
#, python-format
msgid "Host %(host)s is not up or doesn't exist."
msgstr ""

#: manila/exception.py:302
#, python-format
msgid "Quota exceeded: code=%(code)s."
msgstr ""

#: manila/exception.py:309
msgid "Requested share exceeds allowed gigabytes quota."
msgstr ""

#: manila/exception.py:313
msgid "Requested snapshot exceeds allowed gigabytes quota."
msgstr ""

#: manila/exception.py:317
#, python-format
msgid "Maximum number of shares allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:321
#, python-format
msgid "Maximum number of snapshots allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:325
#, python-format
msgid "Maximum number of share-networks allowed (%(allowed)d) exceeded."
msgstr ""

#: manila/exception.py:330
msgid "Unknown Gluster exception."
msgstr ""

#: manila/exception.py:334
#, python-format
msgid "Invalid share: %(reason)s."
msgstr ""

#: manila/exception.py:338
msgid "Maximum number of ports exceeded."
msgstr ""

#: manila/exception.py:342
#, python-format
msgid "Share access %(access_type)s:%(access)s exists."
msgstr ""

#: manila/exception.py:346
#, python-format
msgid "Invalid access_rule: %(reason)s."
msgstr ""

#: manila/exception.py:350
msgid "Deleting $(share_name) share that used."
msgstr ""

#: manila/exception.py:354
#, python-format
msgid "Share backend error: %(msg)s."
msgstr ""

#: manila/exception.py:358 manila/exception.py:413
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: manila/exception.py:362
#, python-format
msgid "Deleting snapshot %(snapshot_name)s that has dependent shares."
msgstr ""

#: manila/exception.py:367
#, python-format
msgid "Invalid share snapshot: %(reason)s."
msgstr ""

#: manila/exception.py:371
msgid "Metadata item is not found."
msgstr ""

#: manila/exception.py:375
msgid "Invalid metadata."
msgstr ""

#: manila/exception.py:379
msgid "Invalid metadata size."
msgstr ""

#: manila/exception.py:383
#, python-format
msgid "Security service %(security_service_id)s could not be found."
msgstr ""

#: manila/exception.py:387
#, python-format
msgid ""
"Failed to associate share network %(share_network_id)s and security "
"service %(security_service_id)s: %(reason)s."
msgstr ""

#: manila/exception.py:392
#, python-format
msgid ""
"Failed to dissociate share network %(share_network_id)s and security "
"service %(security_service_id)s: %(reason)s."
msgstr ""

#: manila/exception.py:397
msgid "Invalid volume."
msgstr ""

#: manila/exception.py:401
#, python-format
msgid "Invalid share type: %(reason)s."
msgstr ""

#: manila/exception.py:405
#, python-format
msgid "Invalid extra_spec: %(reason)s."
msgstr ""

#: manila/exception.py:409
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: manila/exception.py:417
#, python-format
msgid "Share type %(share_type_id)s could not be found."
msgstr ""

#: manila/exception.py:421
#, python-format
msgid "Share type with name %(share_type_name)s could not be found."
msgstr ""

#: manila/exception.py:426
#, python-format
msgid ""
"Share Type %(share_type_id)s has no extra specs with key "
"%(extra_specs_key)s."
msgstr ""

#: manila/exception.py:431
#, python-format
msgid ""
"Share Type %(share_type_id)s deletion is not allowed with shares present "
"with the type."
msgstr ""

#: manila/exception.py:436
#, python-format
msgid "Share Type %(id)s already exists."
msgstr ""

#: manila/exception.py:440
#, python-format
msgid "Cannot create share_type with name %(name)s and specs %(extra_specs)s."
msgstr ""

#: manila/exception.py:445
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: manila/exception.py:449
#, python-format
msgid "Bridge %(bridge)s does not exist."
msgstr ""

#: manila/exception.py:453
msgid "Exception in service instance manager occurred."
msgstr ""

#: manila/exception.py:457
msgid "Service instance is not available."
msgstr ""

#: manila/exception.py:461
msgid "Exception due to NetApp failure."
msgstr ""

#: manila/exception.py:465
#, python-format
msgid "Vserver %(vserver)s is not available."
msgstr ""

#: manila/exception.py:485
msgid "GPFS exception occurred."
msgstr ""

#: manila/exception.py:489
msgid "GPFS Ganesha exception occurred."
msgstr ""

#: manila/exception.py:493
msgid "Ganesha management command failed."
msgstr ""

#: manila/exception.py:502
msgid "Invalid Sqlite database."
msgstr ""

#: manila/exception.py:506
msgid "Exception in SSH protocol negotiation or logic."
msgstr ""

#: manila/exception.py:514
msgid "HDFS exception occurred!"
msgstr ""

#: manila/utils.py:116
#, python-format
msgid ""
"Check whether private key or password are correctly set. Error connecting"
" via ssh: %s"
msgstr ""

#: manila/utils.py:174
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: manila/utils.py:494
#, python-format
msgid "Invalid cidr supplied %s"
msgstr ""

#: manila/utils.py:504
#, python-format
msgid "Provided improper IP version '%s'."
msgstr ""

#: manila/wsgi.py:145
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: manila/wsgi.py:148
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: manila/wsgi.py:151
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: manila/wsgi.py:154
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: manila/wsgi.py:187
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: manila/wsgi.py:333
msgid "You must implement __call__"
msgstr ""

#: manila/api/common.py:88 manila/api/common.py:122
msgid "limit param must be an integer"
msgstr ""

#: manila/api/common.py:91 manila/api/common.py:126
msgid "limit param must be positive"
msgstr ""

#: manila/api/common.py:116
msgid "offset param must be an integer"
msgstr ""

#: manila/api/common.py:130
msgid "offset param must be positive"
msgstr ""

#: manila/api/common.py:158
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: manila/api/xmlutil.py:269
msgid "element is not a child"
msgstr ""

#: manila/api/xmlutil.py:418
msgid "root element selecting a list"
msgstr ""

#: manila/api/xmlutil.py:743
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: manila/api/xmlutil.py:865
msgid "subclasses must implement construct()!"
msgstr ""

#: manila/api/contrib/quotas.py:71
msgid "Quota limit must be -1 or greater."
msgstr ""

#: manila/api/contrib/quotas.py:75
#, python-format
msgid "Quota limit must greater than %s."
msgstr ""

#: manila/api/contrib/quotas.py:78
#, python-format
msgid "Quota limit must less than %s."
msgstr ""

#: manila/api/contrib/quotas.py:151 manila/api/contrib/quotas.py:177
#, python-format
msgid "Quota '%(value)s' for %(key)s should be integer."
msgstr ""

#: manila/api/contrib/quotas.py:159
#, python-format
msgid "Bad key(s) %s in quota_set"
msgstr ""

#: manila/api/contrib/quotas.py:192
#, python-format
msgid ""
"Quota value %(value)s for %(key)s are greater than already used and "
"reserved %(quota_used)s"
msgstr ""

#: manila/api/contrib/share_actions.py:81
msgid "Invalid CN (common name). Must be 1-64 chars long"
msgstr ""

#: manila/api/contrib/share_actions.py:137
msgid "Only 'ip','user',or'cert' access types are supported."
msgstr ""

#: manila/api/contrib/types_extra_specs.py:72
#, python-format
msgid "Invalid extra_spec: %(key)s: %(value)s"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:105
msgid "Request body empty"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:109
#: manila/api/v1/share_metadata.py:76
msgid "Request body and URI mismatch"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:112
#: manila/api/v1/share_metadata.py:80
msgid "Request body contains too many items"
msgstr ""

#: manila/api/contrib/types_extra_specs.py:139
msgid "Required extra specs can't be deleted."
msgstr ""

#: manila/api/contrib/types_extra_specs.py:154
msgid ""
"Key names can only contain alphanumeric characters, underscores, periods,"
" colons and hyphens."
msgstr ""

#: manila/api/contrib/types_manage.py:58
msgid "Type name is not valid."
msgstr ""

#: manila/api/middleware/auth.py:106
msgid "Invalid service catalog json."
msgstr ""

#: manila/api/middleware/sizelimit.py:54 manila/api/middleware/sizelimit.py:63
#: manila/api/middleware/sizelimit.py:77
msgid "Request is too large."
msgstr ""

#: manila/api/openstack/__init__.py:74
msgid "Must specify an ExtensionManager class"
msgstr ""

#: manila/api/openstack/wsgi.py:136 manila/api/openstack/wsgi.py:539
msgid "cannot understand JSON"
msgstr ""

#: manila/api/openstack/wsgi.py:160
msgid "cannot understand XML"
msgstr ""

#: manila/api/openstack/wsgi.py:544
msgid "too many body keys"
msgstr ""

#: manila/api/openstack/wsgi.py:817
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:820 manila/api/openstack/wsgi.py:833
#: manila/api/v1/share_metadata.py:54 manila/api/v1/share_metadata.py:72
#: manila/api/v1/share_metadata.py:97 manila/api/v1/share_metadata.py:119
msgid "Malformed request body"
msgstr ""

#: manila/api/openstack/wsgi.py:830
msgid "Unsupported Content-Type"
msgstr ""

#: manila/api/openstack/wsgi.py:842
msgid "Malformed request url"
msgstr ""

#: manila/api/openstack/wsgi.py:887
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr ""

#: manila/api/openstack/wsgi.py:890
#, python-format
msgid "%(url)s returned a fault: %(e)s"
msgstr ""

#: manila/api/v1/limits.py:138
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: manila/api/v1/limits.py:264
msgid "This request was rate-limited."
msgstr ""

#: manila/api/v1/security_service.py:210
#, python-format
msgid ""
"Cannot update security service %s. It is attached to share network with "
"share server associated. Only 'name' and 'description' fields are "
"available for update."
msgstr ""

#: manila/api/v1/security_service.py:238
#, python-format
msgid ""
"Invalid type %(type)s specified for security service. Valid types are "
"%(types)s"
msgstr ""

#: manila/api/v1/share_metadata.py:38 manila/api/v1/share_metadata.py:115
#: manila/api/v1/share_metadata.py:154
msgid "share does not exist"
msgstr ""

#: manila/api/v1/share_metadata.py:137 manila/api/v1/share_metadata.py:147
msgid "Metadata item was not found"
msgstr ""

#: manila/api/v1/share_networks.py:115
#, python-format
msgid "Can not delete share network %(id)s, it has %(len)s share(s)."
msgstr ""

#: manila/api/v1/share_networks.py:230
msgid ""
"Neutron net data and Nova net data are mutually exclusive. Only one of "
"these are allowed at a time."
msgstr ""

#: manila/api/v1/share_networks.py:254
#, python-format
msgid ""
"Cannot update share network %s. It is used by share servers. Only 'name' "
"and 'description' fields are available for update"
msgstr ""

#: manila/api/v1/share_networks.py:322
#, python-format
msgid "Share networks does not have %s action"
msgstr ""

#: manila/api/v1/share_networks.py:331
msgid "Cannot add security services. Share network is used."
msgstr ""

#: manila/api/v1/share_networks.py:337
#, python-format
msgid ""
"Cannot add security service to share network. Security service with "
"'%(ss_type)s' type already added to '%(sn_id)s' share network"
msgstr ""

#: manila/api/v1/share_networks.py:364
msgid "Cannot remove security services. Share network is used."
msgstr ""

#: manila/api/v1/share_servers.py:142
#, python-format
msgid ""
"Share server's actual status is %(status)s, allowed statuses for deletion"
" are %(allowed_statuses)s."
msgstr ""

#: manila/api/v1/share_types.py:45 manila/api/v1/shares.py:276
msgid "Share type not found."
msgstr ""

#: manila/api/v1/share_types.py:58
msgid "Share type not found"
msgstr ""

#: manila/api/v1/share_types.py:62
msgid "Default share type not found"
msgstr ""

#: manila/common/config.py:83
msgid "Deploy v1 of the Manila API."
msgstr ""

#: manila/common/config.py:86
msgid "Deploy v2 of the Manila API."
msgstr ""

#: manila/common/config.py:186
#, python-format
msgid ""
"Unsupported share protocol '%(share_proto)s' is set as enabled. Available"
" values are %(supported)s. "
msgstr ""

#: manila/common/config.py:191
#, python-format
msgid ""
"No share protocols were specified as enabled. Available values are "
"%(supported)s. "
msgstr ""

#: manila/common/config.py:194
msgid ""
"Please specify one or more protocols using configuration option "
"'enabled_share_protocols."
msgstr ""

#: manila/compute/nova.py:199
#, python-format
msgid "Failed to get Nova VM. %s"
msgstr ""

#: manila/db/sqlalchemy/api.py:85
msgid "Use of empty request context is deprecated"
msgstr ""

#: manila/db/sqlalchemy/api.py:198
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: manila/db/sqlalchemy/api.py:1228 manila/db/sqlalchemy/api.py:1483
#, python-format
msgid "Wrong sorting key provided - '%s'."
msgstr ""

#: manila/db/sqlalchemy/api.py:1235 manila/db/sqlalchemy/api.py:1490
#, python-format
msgid ""
"Wrong sorting data provided: sort key is '%(sort_key)s' and sort "
"direction is '%(sort_dir)s'."
msgstr ""

#: manila/db/sqlalchemy/api.py:1473
#, python-format
msgid "Wrong 'usage' key provided - '%(key)s'. Expected keys are '%(ek)s'."
msgstr ""

#: manila/network/nova_network_plugin.py:71
msgid "'nova_net_id' is not provided with share network."
msgstr ""

#: manila/network/nova_network_plugin.py:130
#, python-format
msgid ""
"No available IP addresses left in network '%(net_id)s' with CIDR "
"%(cidr)s. Requested amount of IPs to be provided '%(amount)s', available "
"only '%(available)s'"
msgstr ""

#: manila/network/nova_network_plugin.py:173
msgid "Nova network is not set"
msgstr ""

#: manila/network/nova_network_plugin.py:189
#, python-format
msgid ""
"'share-network' with id '%s' should not contain Neutron data. Either "
"remove it or use another 'share-network'"
msgstr ""

#: manila/network/nova_network_plugin.py:196
#, python-format
msgid ""
"'share-network' with id '%(sn_id)s' already contains Nova network id "
"'%(provided)s' that is different from what is defined in config "
"'%(allowed)s'. Either remove incorrect network id or set it the same"
msgstr ""

#: manila/network/standalone_network_plugin.py:125
#, python-format
msgid ""
"Configuration option 'standalone_network_plugin_gateway' is required and "
"has improper value '%s'."
msgstr ""

#: manila/network/standalone_network_plugin.py:129
#, python-format
msgid ""
"Configuration option 'standalone_network_plugin_mask' is required and has"
" improper value '%s'."
msgstr ""

#: manila/network/standalone_network_plugin.py:161
#, python-format
msgid "Wrong value for IP range '%s' was provided."
msgstr ""

#: manila/network/standalone_network_plugin.py:166
#, python-format
msgid ""
"Config option 'standalone_network_plugin_allowed_ip_ranges' has incorrect"
" value '%s'"
msgstr ""

#: manila/network/standalone_network_plugin.py:181
#, python-format
msgid ""
"One of provided allowed IP ranges ('%(range)s') does not fit network "
"'%(net)s' combined from gateway '%(gateway)s' and netmask '%(netmask)s'."
msgstr ""

#: manila/network/standalone_network_plugin.py:192
#, python-format
msgid ""
"Configured invalid IP version '%(conf_v)s', network has version "
"'%(net_v)s'"
msgstr ""

#: manila/network/standalone_network_plugin.py:220
#, python-format
msgid ""
"No available IP addresses left in CIDRs %(cidrs)s. Requested amount of "
"IPs to be provided '%(amount)s', available only '%(available)s'."
msgstr ""

#: manila/network/linux/interface.py:37
msgid "Name of Open vSwitch bridge to use."
msgstr ""

#: manila/network/linux/ip_lib.py:395
msgid "No namespace defined for parent"
msgstr ""

#: manila/openstack/common/log.py:287
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: manila/openstack/common/log.py:395
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: manila/openstack/common/log.py:456
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: manila/openstack/common/log.py:707
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: manila/openstack/common/policy.py:97
msgid "The JSON file that defines policies."
msgstr ""

#: manila/openstack/common/policy.py:100
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: manila/openstack/common/policy.py:104
msgid "Directories where policy configuration files are stored"
msgstr ""

#: manila/openstack/common/policy.py:119
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: manila/openstack/common/policy.py:213
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: manila/scheduler/chance.py:50 manila/scheduler/simple.py:90
msgid "Is the appropriate service running?"
msgstr ""

#: manila/scheduler/chance.py:55
msgid "Could not find another host"
msgstr ""

#: manila/scheduler/driver.py:86
msgid "Must implement a fallback schedule"
msgstr ""

#: manila/scheduler/driver.py:90
msgid "Must implement schedule_create_share"
msgstr ""

#: manila/scheduler/driver.py:94
msgid "Must implement get_pools"
msgstr ""

#: manila/scheduler/filter_scheduler.py:82
msgid "Invalid value for 'scheduler_max_attempts', must be >=1"
msgstr ""

#: manila/scheduler/filter_scheduler.py:206
#, python-format
msgid "Exceeded max scheduling attempts %(max_attempts)d for share %(share_id)s"
msgstr ""

#: manila/scheduler/simple.py:78
msgid "Not enough allocatable share gigabytes remaining"
msgstr ""

#: manila/share/api.py:73 manila/volume/cinder.py:232
msgid "status must be 'available'"
msgstr ""

#: manila/share/api.py:92
#, python-format
msgid "Share size '%s' must be an integer and greater than 0"
msgstr ""

#: manila/share/api.py:97
#, python-format
msgid "Share size '%s' must be equal or greater than snapshot size"
msgstr ""

#: manila/share/api.py:104
msgid ""
"Invalid share_type provided (requested type must match source snapshot, "
"or be omitted). You should omit the argument."
msgstr ""

#: manila/share/api.py:113
#, python-format
msgid ""
"Invalid share protocol provided: %(provided)s. It is either disabled or "
"unsupported. Available protocols: %(supported)s"
msgstr ""

#: manila/share/api.py:237
msgid "Share status must be available or error"
msgstr ""

#: manila/share/api.py:242
#, python-format
msgid "Share still has %d dependent snapshots"
msgstr ""

#: manila/share/api.py:269
msgid "must be available"
msgstr ""

#: manila/share/api.py:329
msgid "Share Snapshot status must be 'available' or 'error'."
msgstr ""

#: manila/share/api.py:364
#, python-format
msgid "Wrong metadata filter provided: %s."
msgstr ""

#: manila/share/api.py:373
#, python-format
msgid "Wrong extra specs filter provided: %s."
msgstr ""

#: manila/share/api.py:377
#, python-format
msgid "Wrong sort_key filter provided: '%s'."
msgstr ""

#: manila/share/api.py:381
#, python-format
msgid "Wrong sort_dir filter provided: '%s'."
msgstr ""

#: manila/share/api.py:431
#, python-format
msgid "Wrong '%(k)s' filter provided: '%(v)s'."
msgstr ""

#: manila/share/api.py:463 manila/share/api.py:492
msgid "Share host is None"
msgstr ""

#: manila/share/api.py:466 manila/share/api.py:495
msgid "Share status must be available"
msgstr ""

#: manila/share/api.py:481
#, python-format
msgid "Invalid share access level: %s."
msgstr ""

#: manila/share/api.py:506
msgid "Access policy should be active or in error state"
msgstr ""

#: manila/share/api.py:543
msgid "Metadata property key is blank"
msgstr ""

#: manila/share/api.py:547
msgid "Metadata property key is greater than 255 characters"
msgstr ""

#: manila/share/api.py:551
msgid "Metadata property value is blank"
msgstr ""

#: manila/share/api.py:555
msgid "Metadata property value is greater than 1023 characters"
msgstr ""

#: manila/share/share_types.py:57 manila/share/share_types.py:118
msgid "id cannot be None"
msgstr ""

#: manila/share/share_types.py:130
msgid "name cannot be None"
msgstr ""

#: manila/share/share_types.py:203
#, python-format
msgid "Required extra specs '%s' not specified."
msgstr ""

#: manila/share/share_types.py:211
#, python-format
msgid "Value of required extra_spec %s is not valid"
msgstr ""

#: manila/share/drivers/generic.py:98
#, python-format
msgid ""
"Share server handling is not available. But 'share_server' was provided. "
"'%s'. Share network should not be used."
msgstr ""

#: manila/share/drivers/generic.py:103
msgid ""
"Share server handling is enabled. But 'share_server' is not provided. "
"Make sure you used 'share_network'."
msgstr ""

#: manila/share/drivers/generic.py:108
#, python-format
msgid "Share server '%s' does not have backend details."
msgstr ""

#: manila/share/drivers/generic.py:336
#, python-format
msgid "Volume %s is already attached to another instance"
msgstr ""

#: manila/share/drivers/generic.py:349
#, python-format
msgid "Failed to attach volume %s"
msgstr ""

#: manila/share/drivers/generic.py:353
#, python-format
msgid "Volume have not been attached in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:373
msgid "Error. Ambiguous volumes"
msgstr ""

#: manila/share/drivers/generic.py:393
msgid "Error. Ambiguous volume snaphots"
msgstr ""

#: manila/share/drivers/generic.py:421
#, python-format
msgid "Volume have not been detached in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:444
msgid "Failed to create volume"
msgstr ""

#: manila/share/drivers/generic.py:449
#, python-format
msgid "Volume have not been created in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:461
msgid "Volume is still in use and cannot be deleted now."
msgstr ""

#: manila/share/drivers/generic.py:475
#, python-format
msgid "Volume have not been deleted in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:537
msgid "Failed to create volume snapshot"
msgstr ""

#: manila/share/drivers/generic.py:545
#, python-format
msgid "Volume snapshot have not been created in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:568
#, python-format
msgid "Volume snapshot have not been deleted in %ss. Giving up"
msgstr ""

#: manila/share/drivers/generic.py:692
#, python-format
msgid "NFS server is not installed on %s"
msgstr ""

#: manila/share/drivers/generic.py:783
#, python-format
msgid "Share section %s already defined."
msgstr ""

#: manila/share/drivers/generic.py:815
#: manila/share/drivers/emc/plugins/vnx/connection.py:387
#: manila/share/drivers/emc/plugins/vnx/connection.py:442
#: manila/share/drivers/zfssa/zfssarest.py:326
#: manila/share/drivers/zfssa/zfssarest.py:362
msgid "Only ip access type allowed."
msgstr ""

#: manila/share/drivers/glusterfs.py:173
msgid ""
"glusterfs_target configuration that specifies the GlusterFS volume to be "
"mounted on the Manila host is not set."
msgstr ""

#: manila/share/drivers/glusterfs.py:186
#: manila/share/drivers/glusterfs_native.py:121
msgid "mount.glusterfs is not installed."
msgstr ""

#: manila/share/drivers/glusterfs.py:276
msgid "GlusterFS control mount is not available"
msgstr ""

#: manila/share/drivers/glusterfs.py:361
#, python-format
msgid "Unsupported share type, %s."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:106
msgid ""
"glusterfs_targets list seems to be empty! Add one or more gluster volumes"
" to work with in the glusterfs_targets configuration parameter."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:125
msgid "Error running mount.glusterfs."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:134
msgid ""
"No unused gluster volumes available for use as share! Create share won't "
"be supported unless existing shares are deleted or add one or more "
"gluster volumes to work with in the glusterfs_targets configuration "
"parameter."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:190
#, python-format
msgid ""
"Error in gluster volume set during volume setup. Volume: %(volname)s, "
"Option: %(option)s, rror: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:203
#: manila/share/drivers/glusterfs_native.py:216
#, python-format
msgid ""
"Error in gluster volume set during volume setup. Volume: %(volname)s, "
"Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:233
#, python-format
msgid "Error stopping gluster volume. Volume: %(volname)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:243
#, python-format
msgid "Error starting gluster volume. Volume: %(volname)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:254
msgid "Couldn't find a free gluster volume to use."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:266
msgid "Couldn't find the share in used list."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:278
#, python-format
msgid ""
"Unable to mount gluster volume. gluster_export: %(export)s, Error: "
"%(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:290
#, python-format
msgid "Unable to unmount gluster volume. mount_dir: %(mntdir)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:304
#: manila/share/drivers/glusterfs_native.py:317
#: manila/share/drivers/glusterfs_native.py:357
#: manila/share/drivers/glusterfs_native.py:370
#, python-format
msgid ""
"Error in gluster volume set during _wipe_gluster_vol. Volume: "
"%(volname)s, Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:341
#, python-format
msgid ""
"Error trying to wipe gluster volume. gluster_export: %(export)s, Error: "
"%(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:392
#, python-format
msgid "Error creating share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:416
#, python-format
msgid "Invalid request. Ignoring delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:425
#, python-format
msgid "Error during delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:439
msgid "Only 'cert' access type allowed"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:449
#, python-format
msgid ""
"Error in gluster volume set during allow access. Volume: %(volname)s, "
"Option: %(option)s, access_to: %(access_to)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:469
msgid "Only 'cert' access type allowed for access removal."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:480
#, python-format
msgid ""
"Error in gluster volume reset during deny access. Volume: %(volname)s, "
"Option: %(option)s, Error: %(error)s"
msgstr ""

#: manila/share/drivers/service_instance.py:178
#, python-format
msgid ""
"Wrong value '%(provided)s' for config opt "
"'service_instance_network_helper_type'. Allowed values are %(allowed)s."
msgstr ""

#: manila/share/drivers/service_instance.py:206
msgid "Service instance user is not specified."
msgstr ""

#: manila/share/drivers/service_instance.py:287
#, python-format
msgid ""
"Failed to get service instance IP address. Service network name is "
"'%(net_name)s' and provided data are '%(data)s'."
msgstr ""

#: manila/share/drivers/service_instance.py:332
msgid "Ambiguous security_groups."
msgstr ""

#: manila/share/drivers/service_instance.py:373
#, python-format
msgid "Instance '%(id)s' has not been deleted in %(s)ss. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:405
#, python-format
msgid ""
"SSH connection has not been established to %(server)s in %(time)ss. "
"Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:430
msgid "Ambiguous keypairs."
msgstr ""

#: manila/share/drivers/service_instance.py:456
#, python-format
msgid "Image with name '%s' not found."
msgstr ""

#: manila/share/drivers/service_instance.py:459
#, python-format
msgid "Found more than one image by name '%s'."
msgstr ""

#: manila/share/drivers/service_instance.py:469
msgid "Neither service instance password nor key are available."
msgstr ""

#: manila/share/drivers/service_instance.py:502
#, python-format
msgid "Failed to build service instance '%s'."
msgstr ""

#: manila/share/drivers/service_instance.py:513
#, python-format
msgid "Instance '%(ins)s' has not been spawned in %(timeout)s seconds. Giving up."
msgstr ""

#: manila/share/drivers/service_instance.py:643
msgid "Ambiguous service networks."
msgstr ""

#: manila/share/drivers/service_instance.py:734
msgid "No available cidrs."
msgstr ""

#: manila/share/drivers/service_instance.py:790
msgid "Error. Ambiguous service ports."
msgstr ""

#: manila/share/drivers/service_instance.py:828
msgid "Subnet must have gateway."
msgstr ""

#: manila/share/drivers/service_instance.py:839
msgid "Subnet gateway is not attached to the router."
msgstr ""

#: manila/share/drivers/service_instance.py:862
msgid "Ambiguous service subnets."
msgstr ""

#: manila/share/drivers/service_instance.py:916
msgid "Nova network for service instance is not provided."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:68
#: manila/share/drivers/emc/plugins/vnx/connection.py:168
#: manila/share/drivers/emc/plugins/vnx/connection.py:354
#: manila/share/drivers/hds/sop.py:183
#: manila/share/drivers/huawei/huawei_helper.py:192
#: manila/share/drivers/huawei/huawei_helper.py:536
#: manila/share/drivers/huawei/huawei_helper.py:642
#, python-format
msgid "Invalid NAS protocol supplied: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:85
msgid "No share server found."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:96
#, python-format
msgid "Could not create file system for %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:113
#, python-format
msgid "Could not create CIFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:120
#, python-format
msgid "Could not disable share access. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:125
#, python-format
msgid "CIFS server %s doesn't have interface, so the share is inaccessible."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:143
#, python-format
msgid "Could not create NFS export for share %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:186
#, python-format
msgid "Could not create check point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:227
#, python-format
msgid "Deleting CIFS share %(share_name)s on %(mover)s failed. Reason: %(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:256
#, python-format
msgid ""
"Deleting NFS share %(share_name)s on %(mover_name)s failed. Reason: "
"%(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:309
#, python-format
msgid "Failed to delete file system %(fsid)s. Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:334
#, python-format
msgid "Could not delete check point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:377
#, python-format
msgid "Could not allow CIFS access. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:395
#, python-format
msgid "Could not allow access to NFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:409
msgid "Unsupported share type"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:431
#, python-format
msgid "Could not deny access to CIFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:451
#, python-format
msgid "Could not deny access to NFS share. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:520
#, python-format
msgid "Could not get share server by name %(name)s. Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:546
#, python-format
msgid "Interface creation failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:602
#, python-format
msgid "Could not create VDM %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:611
#, python-format
msgid "Could not get physical device port on mover (id:%s)."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:639
#, python-format
msgid "Failed to create cifs server %(name)s.Reason: %(err)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:654
#, python-format
msgid "Could not create DNS domain. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:743
#, python-format
msgid "Could not find the storage pool by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:753
#, python-format
msgid "Could not find Data Mover by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:765
#, python-format
msgid "Could not find Virtual Data Mover by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:775
#, python-format
msgid "Could not find Data Mover by id: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:784
#, python-format
msgid "Could not get CIFS server list for %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:789
#, python-format
msgid "Could not find the CIFS servers on VDM: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:803
#, python-format
msgid "Could not get file system by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:834
#, python-format
msgid "Copy content from checkpoint to file system failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:854
#, python-format
msgid "Extend the file system failed. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:904
msgid ""
"Unsupported security services. Only support single security service and "
"only support type 'active_directory'"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:912
msgid "Only user access type allowed for cifs share"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:918
msgid "Only single security service with type 'active_directory' supported"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:128
#, python-format
msgid "The request is invalid. Reason: %(reason)s"
msgstr ""

#: manila/share/drivers/ganesha/manager.py:265
#, python-format
msgid "Incomplete export block: value %(val)s of attribute %(key)s is a stub."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:157
#: manila/share/drivers/ibm/gpfs.py:192
#, python-format
msgid "Error running SSH command: %(cmd)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:167
#, python-format
msgid "Can not get the execution path of hdfs. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:177
msgid "Can not get the execution path of hdfs."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:184
msgid "Only HDFS protocol supported!"
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:195
#, python-format
msgid ""
"Failed to create directory in hdfs for the share %(sharename)s. Error: "
"%(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:206
#, python-format
msgid "Failed to set space quota for the share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:217
#, python-format
msgid "Failed to allow snapshot for the share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:254
#, python-format
msgid ""
"Failed to create share %(sharename)s from snapshot %(snapshotname)s. "
"Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:274
#, python-format
msgid ""
"Failed to create snapshot %(snapshotname)s for the share %(sharename)s. "
"Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:290
#, python-format
msgid "Failed to delete share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:306
#, python-format
msgid "Failed to delete snapshot %(snapshotname)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:319
msgid "Only 'user' access type allowed!"
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:330
#, python-format
msgid "The access level %(accesslevel)s was unsupported."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:345
#, python-format
msgid ""
"Failed to set ACL of share %(sharename)s for user: %(username)sError: "
"%(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:364
#, python-format
msgid ""
"Failed to deny ACL of share %(sharename)s for user: %(username)sError: "
"%(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:377
msgid "Failed to check the utility of hdfs."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:384
#, python-format
msgid "Failed to check hdfs state. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:395
msgid ""
"Not specify the hdfs cluster yet! Add the ip of hdfs namenode in the "
"hdfs_namenode_ip configuration parameter."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:402
msgid "HDFS is not in healthy state."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:412
#, python-format
msgid "Failed to check available capacity for hdfs.Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hdfs/hdfs_native.py:423
#, python-format
msgid "Failed to get hdfs capacity info. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/hds/sop.py:79
msgid "job timed out"
msgstr ""

#: manila/share/drivers/hds/sop.py:85
msgid "error getting job status"
msgstr ""

#: manila/share/drivers/hds/sop.py:89
msgid "job errored out"
msgstr ""

#: manila/share/drivers/hds/sop.py:110 manila/share/drivers/hds/sop.py:129
#: manila/share/drivers/hds/sop.py:145 manila/share/drivers/hds/sop.py:166
#: manila/share/drivers/hds/sop.py:222 manila/share/drivers/hds/sop.py:238
#: manila/share/drivers/hds/sop.py:312 manila/share/drivers/hds/sop.py:344
#, python-format
msgid "received error: %s"
msgstr ""

#: manila/share/drivers/hds/sop.py:274
msgid "only IP access type allowed"
msgstr ""

#: manila/share/drivers/hds/sop.py:286
#, python-format
msgid "Unsupported level of access was provided - %s"
msgstr ""

#: manila/share/drivers/hds/sop.py:364
#, python-format
msgid "received error: %(code)s: %(msg)s"
msgstr ""

#: manila/share/drivers/hds/sop.py:371
msgid "connection to SOPAPI timed out"
msgstr ""

#: manila/share/drivers/hp/hp_3par_driver.py:99
msgid "Unsupported configuration.  hp3par_share_ip_address is not set."
msgstr ""

#: manila/share/drivers/hp/hp_3par_driver.py:165
#, python-format
msgid "Invalid protocol. Expected NFS or CIFS. Got %s."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:61
msgid "You must install hp3parclient before using the 3PAR driver."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:70
#, python-format
msgid "Failed to connect to HP 3PAR File Persona Client: %s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:92
#, python-format
msgid "Failed to set SSH options for HP 3PAR File Persona Client: %s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:104
#, python-format
msgid "Failed to get capacity for fpg %(fpg)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:110
#, python-format
msgid "Failed to get capacity for fpg %s."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:128
#, python-format
msgid "Invalid protocol. Expected nfs or smb. Got %s."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:186
#, python-format
msgid "Failed to create fstore %(fstore)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:214
#, python-format
msgid "Failed to setfsquota on %(fstore)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:244
#, python-format
msgid "Failed to create share %(share_name)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:256
#, python-format
msgid "Failed to get fshare %(share_name)s after creating it: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:263
#, python-format
msgid ""
"Failed to get fshare %(share_name)s after creating it. Expected to get 1 "
"fshare.  Got %(total)s."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:290
#, python-format
msgid ""
"Failed to create share from snapshot for FPG/VFS/tag "
"%(fpg)s/%(vfs)s/%(tag)s. Snapshot not found."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:335
#, python-format
msgid "Failed to remove share %(share_name)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:344
#, python-format
msgid "Failed to remove fstore %(fstore)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:358
#, python-format
msgid "Exception during getvfs %(vfs)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:366
#, python-format
msgid "Error while validating FPG/VFS (%(fpg)s/%(vfs)s): %(msg)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:372
#, python-format
msgid ""
"Error while validating FPG/VFS (%(fpg)s/%(vfs)s): Expected 1, got "
"%(total)s."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:394
#, python-format
msgid ""
"Failed to create snapshot for FPG/VFS/fshare %(fpg)s/%(vfs)s/%(fshare)s: "
"Failed to find fshare."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:402
#, python-format
msgid ""
"Failed to create snapshot for FPG/VFS/fshare %(fpg)s/%(vfs)s/%(fshare)s: "
"Share is a read-only share of an existing snapshot."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:418
#, python-format
msgid ""
"Failed to create snapshot for FPG/VFS/fstore %(fpg)s/%(vfs)s/%(fstore)s: "
"%(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:446
#, python-format
msgid ""
"Unexpected exception while getting share list. Cannot delete snapshot "
"without checking for dependent shares first: %s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:467
msgid "Cannot delete snapshot because it has a dependent share."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:479
#, python-format
msgid ""
"Failed to delete snapshot for FPG/VFS/fstore/snapshot "
"%(fpg)s/%(vfs)s/%(fstore)s/%(snapname)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:495
#, python-format
msgid "Unexpected exception calling startfsnapclean for FPG %(fpg)s: %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:503
#, python-format
msgid "Invalid access type.  Expected 'ip' or 'user'.  Actual '%s'."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:509
#, python-format
msgid "Invalid NFS access type.  HP 3PAR NFS supports 'ip'. Actual '%s'."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:548
#, python-format
msgid ""
"Unexpected error:  After ensure_supported_protocol only 'nfs' or 'smb' "
"strings are allowed, but found: %s."
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:555
#, python-format
msgid ""
"Failed to change (%(change)s) access to FPG/share %(fpg)s/%(share)s to "
"%(type)s %(to)s): %(e)s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:598
#, python-format
msgid "Unexpected exception while getting share list: %s"
msgstr ""

#: manila/share/drivers/hp/hp_3par_mediator.py:623
#, python-format
msgid "Unexpected exception while getting snapshots: %s"
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:78
#, python-format
msgid "JSON transfer error: %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:93
#, python-format
msgid "Login error, reason is %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:116
#: manila/share/drivers/huawei/huawei_helper.py:554
#, python-format
msgid ""
"%(err)s\n"
"result: %(res)s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:123
#, python-format
msgid "%s \"data\" was not in result."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:153
#, python-format
msgid "File write error %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:310
#, python-format
msgid "Invalid resource pool: %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:389
#, python-format
msgid ""
"Config file is wrong. Filesystem type must be \"Thin\" or \"Thick\". "
"AllocType:%(fetchtype)s"
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:481
msgid "Only IP access type is allowed for NFS shares."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:485
msgid "Only USER access type is allowed for CIFS shares."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:492
msgid "Can not get share."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:687
msgid "_check_conf_file: Config file invalid. Product must be set to V3."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:694
msgid ""
"_check_conf_file: Config file invalid. RestURL, UserName and UserPassword"
" must be set."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:701
msgid "_check_conf_file: Config file invalid. StoragePool must be set."
msgstr ""

#: manila/share/drivers/huawei/huawei_nas.py:59
msgid "Huawei configuration missing."
msgstr ""

#: manila/share/drivers/huawei/huawei_nas.py:135
msgid "Create a snapshot,share fs id is empty."
msgstr ""

#: manila/share/drivers/huawei/huawei_nas.py:244
#, python-format
msgid "_wait_for_condition: %s timed out."
msgstr ""

#: manila/share/drivers/ibm/ganesha_utils.py:152
#, python-format
msgid ""
"Invalid export config file %(configpath)s: %(exports)s export clauses "
"found, but %(export_ids)s export_ids."
msgstr ""

#: manila/share/drivers/ibm/ganesha_utils.py:204
#, python-format
msgid "Invalid IP access string %s."
msgstr ""

#: manila/share/drivers/ibm/ganesha_utils.py:243
#: manila/share/drivers/ibm/ganesha_utils.py:254
#: manila/share/drivers/ibm/ganesha_utils.py:272
#, python-format
msgid "Failed while publishing ganesha config locally. Error: %s."
msgstr ""

#: manila/share/drivers/ibm/ganesha_utils.py:285
#, python-format
msgid "Failed while publishing ganesha config on remote server. Error: %s."
msgstr ""

#: manila/share/drivers/ibm/ganesha_utils.py:335
#, python-format
msgid "Could not restart service %(service)s on %(server)s: %(excmsg)s"
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:233 manila/share/drivers/ibm/gpfs.py:242
#, python-format
msgid "Failed to check GPFS state. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:255
#, python-format
msgid "%(path)s is not a directory. Error: %(excmsg)s"
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:266
#, python-format
msgid "%(dir)s is not on GPFS filesystem. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:292
#, python-format
msgid "Failed to get GPFS device for %(fspath)s.Error: %(excmsg)s"
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:318
#, python-format
msgid ""
"Failed to create fileset on %(fsdev)s for the share %(sharename)s. Error:"
" %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:329
#, python-format
msgid "Failed to link fileset for the share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:339
#, python-format
msgid "Failed to set quota for the share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:348
#, python-format
msgid "Failed to set permissions for share %(sharename)s. Error: %(excmsg)."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:371
#, python-format
msgid "Failed unlink fileset for share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:381
#, python-format
msgid "Failed delete fileset for share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:392
#, python-format
msgid "Failed to check available capacity for %(path)s.Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:415
#, python-format
msgid "Failed to create snapshot %(snapshot)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:430
#, python-format
msgid "Failed to delete snapshot %(snapshot)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:444
#, python-format
msgid ""
"Failed to create share %(share)s from snapshot %(snapshot)s. Error: "
"%(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:503
msgid "GPFS is not active."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:508
msgid "gpfs_share_export_ip must be specified."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:514
#, python-format
msgid "%s must be an absolute path."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:519
#, python-format
msgid "%s is not a directory."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:524
#, python-format
msgid "%s is not on GPFS. Perhaps GPFS not mounted."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:530
#, python-format
msgid ""
"Invalid gpfs_nfs_server_type value: %s. Valid values are: \"KNFS\", "
"\"GNFS\"."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:537
msgid "Missing value for gpfs_nfs_server_list."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:562
#, python-format
msgid "Share protocol %s not supported by GPFS driver."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:615
#, python-format
msgid "NFS server not found. Error: %s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:645
#, python-format
msgid "Unknown metadata key %s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:667
#, python-format
msgid "Failed to check exports on the systems.  Error: %s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:685
#, python-format
msgid "Failed to allow access for share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:699
#, python-format
msgid "Failed to deny access for share %(sharename)s. Error: %(excmsg)s."
msgstr ""

#: manila/share/drivers/netapp/common.py:65
msgid "Required configuration not found."
msgstr ""

#: manila/share/drivers/netapp/common.py:93
msgid ""
"Driver mode was not specified and a default value could not be determined"
" from the specified storage family."
msgstr ""

#: manila/share/drivers/netapp/common.py:116
#, python-format
msgid "Storage family %s is not supported."
msgstr ""

#: manila/share/drivers/netapp/common.py:122
#, python-format
msgid ""
"Driver mode %(driver_mode)s is not supported for storage family "
"%(storage_family)s."
msgstr ""

#: manila/share/drivers/netapp/utils.py:55
#, python-format
msgid "Configuration value %s is not set."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/api.py:458
#, python-format
msgid "No element by given name %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/api.py:478
msgid "Not a valid value for NaElement."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/api.py:482
msgid "NaElement name cannot be null."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/api.py:525
msgid "Type cannot be converted into NaElement."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/api.py:558
msgid "Requires an NaServer instance."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:134
#, python-format
msgid "Could not determine root volume name for Vserver %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:211
#, python-format
msgid "Cannot delete Vserver. Vserver %s has shares."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:272
#, python-format
msgid "Data port does not exist for node %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:291
msgid "Could not list aggregates."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:351
#, python-format
msgid "Failed to create VLAN %(vlan)s on port %(port)s. %(err_msg)s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:580
#, python-format
msgid "Unsupported security service type %s for Data ONTAP driver"
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:639
#, python-format
msgid "Failed to create CIFS server entry. %s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:665
#, python-format
msgid "Failed to create Kerberos realm. %s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:678
msgid "Cannot set up Kerberos. There are no LIFs configured."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:715
#, python-format
msgid "Failed to configure DNS. %s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:819
#, python-format
msgid "Could not find aggregate for volume %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:894
#, python-format
msgid "Could not find unique snapshot %(snap)s on volume %(vol)s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:269
#, python-format
msgid "Invalid NAS protocol supplied: %s. "
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:285
#, python-format
msgid "The protocol %(protocol)s is not licensed on controller %(host)s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:322
msgid "Pool is not available in the share host field."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:360
#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:376
#, python-format
msgid ""
"Invalid value \"%(value)s\" for extra_spec \"%(key)s\" in share_type "
"%(type_id)s for share %(share_id)s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:487
#, python-format
msgid ""
"Cannot find network interfaces for Vserver %(vserver)s and protocol "
"%(proto)s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:53
msgid ""
"Cluster credentials must be specified in the configuration when the "
"driver is managing share servers."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:64
msgid "Share server not provided."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:71
msgid ""
"Vserver name is absent in backend details. Please check whether Vserver "
"was created properly."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:109
#, python-format
msgid "Vserver %s already exists."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_single_svm.py:50
msgid ""
"Vserver must be specified in the configuration when the driver is not "
"managing share servers."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_single_svm.py:62
msgid ""
"Vserver specified in the configuration does not match supplied "
"credentials."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_single_svm.py:80
msgid ""
"Share server must not be passed to the driver when the driver is not "
"managing share servers."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_single_svm.py:85
msgid "Vserver not specified in configuration."
msgstr ""

#: manila/share/drivers/netapp/dataontap/protocols/cifs_cmode.py:50
msgid ""
"Cluster Mode supports only 'user' type for share access rules with CIFS "
"protocol."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:58
#, python-format
msgid "Rest call to %(host)s %(path)s failed.Status: %(status)d Message: %(data)s"
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:91
#, python-format
msgid "Cannot enable %s service."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:99
#, python-format
msgid "Error creating share: %(share)s on pool: %(pool)s. Not enough space."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:115
#, python-format
msgid ""
"Error getting pool stats: pool: %(pool)s return code: %(ret.status)d "
"message: %(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:125
#, python-format
msgid "Error pool ownership: pool %(pool)s is not owned by %(host)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:144
#, python-format
msgid ""
"Error getting project stats: pool: %(pool)s project: %(project)s return "
"code: %(ret.status)d message: %(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:167
#, python-format
msgid ""
"Error creating project: %(project)s on pool: %(pool)s return code: "
"%(ret.status)d message: %(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:198
#, python-format
msgid ""
"Error creating share: %(name)s return code: %(ret.status)d message: "
"%(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:207
#, python-format
msgid "Share with name %s already exists."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:223
#, python-format
msgid "Error modifying %(arg)s  of share %(id)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:256
#, python-format
msgid ""
"Error creating snapshot: %(snapshot)s on share: %(share)s to pool: "
"%(pool)s project: %(project)s return code: %(ret.status)d message: "
"%(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:276
#, python-format
msgid ""
"Error deleting snapshot: %(snapshot)s on share: %(share)s to pool: "
"%(pool)s project: %(project)s  return code: %(ret.status)d message: "
"%(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:300
#, python-format
msgid ""
"Error cloning snapshot: %(snapshot)s on share: %(share)s of Pool: "
"%(pool)s project: %(project)s return code: %(ret.status)d message: "
"%(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssashare.py:102
#, python-format
msgid "%s is required in manila.conf"
msgstr ""

#: manila/share/drivers/zfssa/zfssashare.py:172
#, python-format
msgid "Protocol %s is not supported."
msgstr ""

#: manila/share/drivers/zfssa/zfssashare.py:277
#, python-format
msgid "Share %s doesn't exists."
msgstr ""

#: manila/volume/cinder.py:227
msgid "status must be 'in-use'"
msgstr ""

#: manila/volume/cinder.py:235
msgid "already attached"
msgstr ""

#: manila/volume/cinder.py:239
msgid "Instance and volume not in same availability_zone"
msgstr ""

#: manila/volume/cinder.py:244
msgid "already detached"
msgstr ""

#: manila/volume/cinder.py:308
#, python-format
msgid ""
"Error in creating cinder volume. Cinder volume type %s not exist. Check "
"parameter cinder_volume_type in configuration file."
msgstr ""

