# Translations template for manila.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the manila project.
#
# Translators:
# Andreas Jaeger <jaegerandi@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Manila\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-13 06:20+0000\n"
"PO-Revision-Date: 2015-03-12 15:24+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: German (http://www.transifex.com/projects/p/manila/language/"
"de/)\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: manila/exception.py:94
msgid "Exception in string format operation."
msgstr ""

#: manila/exception.py:96
#, python-format
msgid "%(name)s: %(value)s"
msgstr "%(name)s: %(value)s"

#: manila/manager.py:161
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr "Fehler während %(full_task_name)s: %(e)s"

#: manila/quota.py:985
#, python-format
msgid "Failed to commit reservations %s"
msgstr ""

#: manila/quota.py:1009
#, python-format
msgid "Failed to roll back reservations %s"
msgstr ""

#: manila/service.py:237 manila/openstack/common/service.py:269
msgid "Unhandled exception"
msgstr "Nicht behandelte Exception"

#: manila/service.py:508
msgid "Recovered model server connection!"
msgstr ""

#: manila/service.py:514
msgid "model server went away"
msgstr ""

#: manila/api/extensions.py:246
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: manila/api/middleware/fault.py:45
#, python-format
msgid "Caught error: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:583
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: manila/api/v1/share_networks.py:128
msgid "Failed to update usages deleting share-network."
msgstr ""

#: manila/db/migrations/alembic/versions/162a3e673105_manila_init.py:402
msgid "Exception while creating table."
msgstr "Ausnahme beim Anlegen einer Tabelle."

#: manila/db/migrations/alembic/versions/30cb96d995fa_add_is_public_column_for_share.py:42
msgid "Column shares.is_public not created!"
msgstr ""

#: manila/db/migrations/alembic/versions/30cb96d995fa_add_is_public_column_for_share.py:50
msgid "Column shares.is_public not dropped!"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:45
#, python-format
msgid "Column |%s| not created!"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:65
#, python-format
msgid "Table |%s| not created!"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:73
msgid "share_types.is_public column not dropped"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:79
msgid "share_type_projects table not dropped"
msgstr ""

#: manila/db/sqlalchemy/api.py:2223
#, python-format
msgid "ShareType %s deletion failed, ShareType in use."
msgstr ""

#: manila/network/linux/interface.py:175 manila/network/linux/interface.py:217
#, python-format
msgid "Failed unplugging interface '%s'"
msgstr ""

#: manila/network/linux/ovs_lib.py:49
#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr ""

#: manila/network/neutron/api.py:167
#, python-format
msgid "Neutron error creating port on network %s"
msgstr ""

#: manila/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "in Klasse fixed duration looping call"

#: manila/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "in  Klasse dynamic looping call"

#: manila/openstack/common/policy.py:535 manila/openstack/common/policy.py:815
#, python-format
msgid "Failed to understand rule %s"
msgstr "Fehler die Regel %s zu verstehen."

#: manila/openstack/common/policy.py:545
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Kein Handler für Matches der Art %s"

#: manila/scheduler/filter_scheduler.py:228
#, python-format
msgid ""
"Error scheduling %(share_id)s from last share-service: %(last_host)s : "
"%(exc)s"
msgstr ""

#: manila/scheduler/scheduler_options.py:68
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: manila/scheduler/scheduler_options.py:78
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: manila/scheduler/filters/capacity_filter.py:39
msgid "Free capacity not set: volume node info collection broken."
msgstr ""

#: manila/share/api.py:236
msgid "Failed to update quota for deleting share"
msgstr ""

#: manila/share/driver.py:143
#, python-format
msgid "Recovering from a failed execute. Try number %s"
msgstr ""

#: manila/share/manager.py:99
#, python-format
msgid "Failed to fetch pool name for share: %(share)s. Error: %(error)s."
msgstr ""

#: manila/share/manager.py:128
#, python-format
msgid ""
"Caught exception trying ensure share '%(s_id)s'. Exception: \n"
"%(e)s."
msgstr ""

#: manila/share/manager.py:145
#, python-format
msgid ""
"Unexpected exception during share access allow operation. Share id is "
"'%(s_id)s', access rule type is '%(ar_type)s', access rule id is "
"'%(ar_id)s', exception is '%(e)s'."
msgstr ""

#: manila/share/manager.py:260
#, python-format
msgid "Share server %s does not exist."
msgstr "Share Server %s existiert nicht."

#: manila/share/manager.py:270
msgid "Failed to get share server for share creation."
msgstr ""

#: manila/share/manager.py:289
#, python-format
msgid "Share %s failed on creation."
msgstr ""

#: manila/share/manager.py:335
msgid "Failed to update usages deleting share"
msgstr ""

#: manila/share/manager.py:408
msgid "Failed to update usages deleting snapshot"
msgstr ""

#: manila/share/manager.py:580
#, python-format
msgid "Share server '%s' failed on deletion."
msgstr ""

#: manila/share/share_types.py:53
#, python-format
msgid "DB error: %s"
msgstr "Datenbank Fehler: %s"

#: manila/share/share_types.py:90
#, python-format
msgid "Share type %(share_type)s has invalid required extra specs: %(error)s"
msgstr ""

#: manila/share/share_types.py:162
#, python-format
msgid ""
"Default share type is not found, please check default_share_type config: %s"
msgstr ""

#: manila/share/drivers/generic.py:249
#, python-format
msgid "Failed to sync mount files on server '%s'."
msgstr ""

#: manila/share/drivers/generic.py:256
#, python-format
msgid "Failed to mount all shares on server '%s'."
msgstr ""

#: manila/share/drivers/generic.py:369
#, python-format
msgid ""
"Expected only one volume in volume list with name '%(name)s', but got more "
"than one in a result - '%(result)s'."
msgstr ""

#: manila/share/drivers/generic.py:387
#, python-format
msgid ""
"Expected only one volume snapshot in list with name '%(name)s', but got more "
"than one in a result - '%(result)s'."
msgstr ""

#: manila/share/drivers/glusterfs.py:136
#, python-format
msgid "Error retrieving volume info: %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:198
#, python-format
msgid ""
"Error in tuning GlusterFS volume to enable creation of shares of specific "
"size: %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:256
#, python-format
msgid "Could not mount the Gluster volume %s"
msgstr "Konnte Gluster Volume %s nicht mounten"

#: manila/share/drivers/glusterfs.py:309
#, python-format
msgid "Unable to create share %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:323
#, python-format
msgid ""
"Cannot cleanup share, %s, that errored out during its creation, but exists "
"in GlusterFS volume."
msgstr ""

#: manila/share/drivers/glusterfs.py:335
#, python-format
msgid "Unable to delete share %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:389
#, python-format
msgid ""
"Error in tuning GlusterFS volume to prevent exporting the entire volume: %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:454
#, python-format
msgid "Error in gluster volume set: %s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:568
#, python-format
msgid "Could not setup server. Reason: %s."
msgstr "Kann Server nicht aufsetzen. Grund: %s."

#: manila/share/drivers/emc/plugins/vnx/connection.py:690
#, python-format
msgid "Could not find CIFS server by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:735
msgid "Could not get storage pool list."
msgstr "Storage Pool Liste konnte nicht abgerufen werden."

#: manila/share/drivers/emc/plugins/vnx/connection.py:862
#, python-format
msgid "Could not get mount point. Reason: %s."
msgstr "Mountpunkt konnten nicht abgerufen werden. Grund: %s."

#: manila/share/drivers/emc/plugins/vnx/helper.py:88
#, python-format
msgid ""
"REQ: [%(method)s] %(url)s %(req_hdrs)s\n"
"REQ BODY: %(req_b)s\n"
"RESP: [%(code)s] %(resp_hdrs)s\n"
"RESP BODY: %(resp_b)s\n"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:1158
#, python-format
msgid "Error running SSH command: %s"
msgstr ""

#: manila/share/drivers/ganesha/manager.py:190
#, python-format
msgid ""
"Error while executing management command on Ganesha node %(tag)s: %(msg)s."
msgstr ""

#: manila/share/drivers/ganesha/manager.py:331
#, python-format
msgid "Invalid export database on Ganesha node %(tag)s: %(db)s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:72
#, python-format
msgid "Bad response from server: %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:164
#, python-format
msgid "Bad response from change file: %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:353
#, python-format
msgid "Read Huawei config file(%(filename)s) for Manila error: %(err)s"
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:731
#, python-format
msgid "Invalid metadata %(attr)s for share %(share)s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_base.py:68
#, python-format
msgid "Could not get licenses list. %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:193
#, python-format
msgid "Vserver %s does not exist."
msgstr "Vserver %s existiert nicht."

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:204
#, python-format
msgid "Volume %s is already offline."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:233
#, python-format
msgid "CIFS server does not exist for Vserver %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:713
msgid "DNS exists for Vserver."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:137
#, python-format
msgid "Neither NFS nor CIFS is licensed on %(backend)s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:126
msgid "Failed to create network interface(s)."
msgstr ""

#: manila/share/drivers/netapp/dataontap/protocols/cifs_cmode.py:73
#, python-format
msgid "User %s does not exist."
msgstr "Benutzer %s existiert nicht."

#: manila/share/drivers/netapp/dataontap/protocols/cifs_cmode.py:75
#, python-format
msgid "Rule %s does not exist."
msgstr "Regel %s existiert nicht."

#: manila/share/drivers/zfssa/zfssarest.py:237
#, python-format
msgid ""
"Error deleting share: %(share)s to pool: %(pool)s project: %(project)s "
"return code: %(ret.status)d message: %(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssashare.py:264
#, python-format
msgid "snapshot %s: has clones"
msgstr ""
